name: Cargo Build & Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 for Rust
on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: List files
        run: |
          ls .
      - run: cargo build --verbose
      - run: cargo test --verbose